spring:
  application:
        name: ka-back
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER:http://host.docker.internal:5028/realms/kaserv}

server:
  port: 5027