spring:
  application:
        name: kaserv-springback
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER:http://ka-keycloak:8080/realms/kaserv}

server:
  port: 5027